"""WebSocket endpoints for real-time data streaming."""

import asyncio
import json
import logging
import time

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from app.config import get_settings
from app.services.camera_interface import get_camera_service
from app.services.camera_mock import ThermalFrame
from app.services.websocket_manager import ws_manager
from app.services.alert_engine import alert_engine

logger = logging.getLogger(__name__)
router = APIRouter()


@router.websocket("/ws/cameras/{camera_id}")
async def camera_feed(websocket: WebSocket, camera_id: str) -> None:
    """Stream live thermal frames for a specific camera.

    Sends JSON frames at ~10fps with thermal matrix data,
    min/max/avg temperatures, and timestamp.
    """
    channel = f"camera:{camera_id}"
    await ws_manager.connect(websocket, channel)

    camera_service = get_camera_service(get_settings().CAMERA_MODE)
    camera_service.register_camera(camera_id)
    camera_service.start(camera_id)

    try:
        while True:
            frame: ThermalFrame = camera_service.generate_frame(camera_id)
            body_temp = camera_service.get_body_temperature(camera_id)

            data = {
                "type": "thermal_frame",
                "camera_id": camera_id,
                "timestamp": frame.timestamp,
                "width": frame.width,
                "height": frame.height,
                "min_temp": frame.min_temp,
                "max_temp": frame.max_temp,
                "avg_temp": frame.avg_temp,
                "body_temperature": body_temp,
                "matrix": frame.matrix,
            }

            await websocket.send_json(data)
            await asyncio.sleep(0.1)  # ~10 fps

    except WebSocketDisconnect:
        logger.info(f"Camera feed disconnected: {camera_id}")
    except Exception as e:
        logger.error(f"Camera feed error for {camera_id}: {e}")
    finally:
        camera_service.stop(camera_id)
        ws_manager.disconnect(websocket, channel)


@router.websocket("/ws/alerts")
async def alert_stream(websocket: WebSocket) -> None:
    """Stream real-time alert notifications.

    Pushes new alerts as they are generated by the alert engine.
    """
    channel = "alerts"
    await ws_manager.connect(websocket, channel)

    try:
        while True:
            # Keep connection alive, alerts are pushed via ws_manager
            data = await websocket.receive_text()
            # Client can send acknowledgment messages
            try:
                msg = json.loads(data)
                if msg.get("action") == "acknowledge":
                    logger.info(f"Alert acknowledged via WS: {msg.get('alert_id')}")
            except json.JSONDecodeError:
                pass

    except WebSocketDisconnect:
        logger.info("Alert stream disconnected")
    except Exception as e:
        logger.error(f"Alert stream error: {e}")
    finally:
        ws_manager.disconnect(websocket, channel)


@router.websocket("/ws/system")
async def system_health_stream(websocket: WebSocket) -> None:
    """Stream system health updates every 5 seconds."""
    from app.services.system_monitor import system_monitor

    channel = "system"
    await ws_manager.connect(websocket, channel)

    try:
        while True:
            health = system_monitor.get_full_health()
            health["type"] = "system_health"
            health["timestamp"] = time.time()

            await websocket.send_json(health)
            await asyncio.sleep(5)

    except WebSocketDisconnect:
        logger.info("System health stream disconnected")
    except Exception as e:
        logger.error(f"System health stream error: {e}")
    finally:
        ws_manager.disconnect(websocket, channel)
