import type { Report } from '@/types';

const REPORT_SECTIONS = [
  'Temperature Summary',
  'Alert History',
  'Heat Timeline',
  'Camera Uptime',
  'Ladle Life Status',
  'Anomaly Highlights',
  'Operator Notes',
];

export function downloadReportPdf(report: Report): void {
  const canvas = document.createElement('canvas');
  const dpi = 2;
  const pageW = 595 * dpi; // A4 width in points
  const pageH = 842 * dpi; // A4 height
  canvas.width = pageW;
  canvas.height = pageH;
  const ctx = canvas.getContext('2d')!;

  // --- Background ---
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, pageW, pageH);

  // --- Header band ---
  ctx.fillStyle = '#0a0e17';
  ctx.fillRect(0, 0, pageW, 120 * dpi);
  ctx.fillStyle = '#3b82f6';
  ctx.fillRect(0, 120 * dpi, pageW, 4 * dpi);

  // --- Title ---
  ctx.fillStyle = '#ffffff';
  ctx.font = `bold ${28 * dpi}px Inter, system-ui, sans-serif`;
  ctx.fillText('INFRASENSE', 40 * dpi, 50 * dpi);
  ctx.font = `${14 * dpi}px Inter, system-ui, sans-serif`;
  ctx.fillStyle = '#94a3b8';
  ctx.fillText('LHF Thermal Monitoring System — JSW Vijayanagar SMS', 40 * dpi, 75 * dpi);
  ctx.font = `bold ${18 * dpi}px Inter, system-ui, sans-serif`;
  ctx.fillStyle = '#f1f5f9';
  ctx.fillText(report.title, 40 * dpi, 105 * dpi);

  let y = 155 * dpi;
  const leftMargin = 40 * dpi;

  // --- Report Metadata ---
  ctx.fillStyle = '#f8f9fa';
  ctx.fillRect(leftMargin, y, pageW - 80 * dpi, 80 * dpi);
  ctx.strokeStyle = '#e5e7eb';
  ctx.lineWidth = 1 * dpi;
  ctx.strokeRect(leftMargin, y, pageW - 80 * dpi, 80 * dpi);

  ctx.font = `${11 * dpi}px Inter, system-ui, sans-serif`;
  ctx.fillStyle = '#6b7280';
  ctx.fillText('Report Type:', leftMargin + 15 * dpi, y + 20 * dpi);
  ctx.fillText('Date Range:', leftMargin + 15 * dpi, y + 40 * dpi);
  ctx.fillText('Generated:', leftMargin + 15 * dpi, y + 60 * dpi);

  ctx.fillStyle = '#111827';
  ctx.font = `bold ${11 * dpi}px Inter, system-ui, sans-serif`;
  ctx.fillText(report.type.charAt(0).toUpperCase() + report.type.slice(1), leftMargin + 110 * dpi, y + 20 * dpi);
  ctx.fillText(`${report.dateFrom.split('T')[0]} to ${report.dateTo.split('T')[0]}`, leftMargin + 110 * dpi, y + 40 * dpi);
  ctx.fillText(report.generatedAt.split('T')[0] + ' ' + (report.generatedAt.split('T')[1]?.substring(0, 8) || ''), leftMargin + 110 * dpi, y + 60 * dpi);

  if (report.emailedTo.length > 0) {
    ctx.fillStyle = '#6b7280';
    ctx.font = `${11 * dpi}px Inter, system-ui, sans-serif`;
    ctx.fillText('Emailed To:', leftMargin + 300 * dpi, y + 20 * dpi);
    ctx.fillStyle = '#111827';
    ctx.font = `bold ${11 * dpi}px Inter, system-ui, sans-serif`;
    ctx.fillText(report.emailedTo.join(', '), leftMargin + 390 * dpi, y + 20 * dpi);
  }

  y += 100 * dpi;

  // --- Sections ---
  REPORT_SECTIONS.forEach((section, idx) => {
    // Section header
    ctx.fillStyle = '#3b82f6';
    ctx.fillRect(leftMargin, y, 4 * dpi, 20 * dpi);
    ctx.fillStyle = '#111827';
    ctx.font = `bold ${14 * dpi}px Inter, system-ui, sans-serif`;
    ctx.fillText(`${idx + 1}. ${section}`, leftMargin + 12 * dpi, y + 16 * dpi);
    y += 30 * dpi;

    // Simulated content
    ctx.fillStyle = '#4b5563';
    ctx.font = `${10 * dpi}px Inter, system-ui, sans-serif`;

    const lines = generateSectionContent(section);
    for (const line of lines) {
      ctx.fillText(line, leftMargin + 12 * dpi, y + 12 * dpi);
      y += 16 * dpi;
    }

    y += 15 * dpi;

    // Check if we need more space
    if (y > pageH - 60 * dpi) return;
  });

  // --- Footer ---
  ctx.fillStyle = '#e5e7eb';
  ctx.fillRect(0, pageH - 40 * dpi, pageW, 1 * dpi);
  ctx.fillStyle = '#9ca3af';
  ctx.font = `${9 * dpi}px Inter, system-ui, sans-serif`;
  ctx.fillText('Generated by InfraSense — LHF Thermal Monitoring System', leftMargin, pageH - 20 * dpi);
  ctx.fillText(`Page 1 of 1`, pageW - 120 * dpi, pageH - 20 * dpi);

  // --- Download ---
  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.title.replace(/[^a-zA-Z0-9-_ ]/g, '')}.png`;
    a.click();
    URL.revokeObjectURL(url);
  }, 'image/png');
}

function generateSectionContent(section: string): string[] {
  switch (section) {
    case 'Temperature Summary':
      return [
        'Peak Temperature: 1,385°C (LHF-1 North, Camera Cam-1)',
        'Average Temperature: 1,265°C across all monitoring zones',
        'Minimum Temperature: 980°C (LHF-2 South, idle period)',
        'Readings above threshold (1,350°C): 12 occurrences',
      ];
    case 'Alert History':
      return [
        'Total Alerts Triggered: 5 (2 Critical, 2 Warning, 1 Info)',
        'Temperature Breach: 2 alerts — LHF-1 Rim Section A exceeded 1,350°C',
        'Rapid Spike: 1 alert — +65°C in 20 seconds at LHF-1 Center',
        'Camera Offline: 1 alert — LHF-2 South offline for 75 minutes',
        'All critical alerts acknowledged within 3 minutes',
      ];
    case 'Heat Timeline':
      return [
        'Total Heats Processed: 3 (H-4519, H-4520, H-4521)',
        'Average Heat Duration: 43 minutes',
        'Longest Heat: H-4521 — 45 min (LHF-1, flagged for review)',
        'PLC trigger success rate: 100% (2 auto, 1 manual)',
      ];
    case 'Camera Uptime':
      return [
        'LHF-1 North (Cam-1): 99.8% uptime',
        'LHF-1 East (Cam-2): 99.5% uptime',
        'LHF-1 South (Cam-3): 98.2% uptime',
        'LHF-1 West (Cam-4): 99.9% uptime',
        'LHF-2 North (Cam-5): 97.5% uptime',
        'LHF-2 South (Cam-6): 85.3% uptime — REQUIRES ATTENTION',
      ];
    case 'Ladle Life Status':
      return [
        'L-087: 42/100 uses — No maintenance required',
        'L-052: 78/100 uses — Approaching maintenance threshold',
        'L-034: 15/100 uses — Healthy',
        'L-098: 91/100 uses — MAINTENANCE DUE (recurring hot spots detected)',
      ];
    case 'Anomaly Highlights':
      return [
        'Heat H-4521: Rim section exceeded safe threshold by 35°C for 8 minutes',
        'Ladle L-098: Recurring hot spot at position (0.3, 0.7) across 5 heats',
        'Camera Cam-6: Intermittent disconnection — check GigE cable',
      ];
    case 'Operator Notes':
      return [
        'Night shift: Camera 6 went offline at 09:15, IT team notified',
        'LHF-1 ran 3 heats, all normal except H-4521 (rim breach)',
        'PLC signals working fine throughout the shift',
      ];
    default:
      return ['No data available for this section.'];
  }
}
